version: "3.7"

services:
  galaxy-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=galaxy
      - POSTGRES_USER=galaxy
      - POSTGRES_PASSWORD=${DB_PASSWD:-galaxy}
    volumes:
      - ./machines/eb-app-api/home/api/galaxy/database/02-create-galaxy-tables.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - data:/var/lib/postgresql/data
    networks:
      intranet:

  galaxy-api-adm:
    image: ghcr.io/emrahcom/galaxy-kc/galaxy-api-adm
    environment:
      - ALLOW_UNSECURE_CERT
      - API_SECRET
      - API_TIMEOUT
      - DB_HOST
      - DB_PASSWD
      - GALAXY_FQDN
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_ORIGIN
      - KEYCLOAK_REALM
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-adm-http.entrypoints=reverse-proxy-http"
      - "traefik.http.routers.api-adm-http.rule=PathPrefix(`/api/adm`)"
      - "traefik.http.routers.api-adm-https.entrypoints=reverse-proxy-https"
      - "traefik.http.routers.api-adm-https.rule=PathPrefix(`/api/adm`)"
      - "traefik.http.routers.api-adm-https.tls=true"
    depends_on:
      - galaxy-db
    networks:
      intranet:

  galaxy-api-pri:
    image: ghcr.io/emrahcom/galaxy-kc/galaxy-api-pri
    environment:
      - API_SECRET
      - DB_HOST
      - DB_PASSWD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-pri-http.entrypoints=reverse-proxy-http"
      - "traefik.http.routers.api-pri-http.rule=PathPrefix(`/api/pri`)"
      - "traefik.http.routers.api-pri-https.entrypoints=reverse-proxy-https"
      - "traefik.http.routers.api-pri-https.rule=PathPrefix(`/api/pri`)"
      - "traefik.http.routers.api-pri-https.tls=true"
    depends_on:
      - galaxy-db
    networks:
      intranet:

  galaxy-api-pub:
    image: ghcr.io/emrahcom/galaxy-kc/galaxy-api-pub
    environment:
      - DB_HOST
      - DB_PASSWD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-pub-http.entrypoints=reverse-proxy-http"
      - "traefik.http.routers.api-pub-http.rule=PathPrefix(`/api/pub`)"
      - "traefik.http.routers.api-pub-https.entrypoints=reverse-proxy-https"
      - "traefik.http.routers.api-pub-https.rule=PathPrefix(`/api/pub`)"
      - "traefik.http.routers.api-pub-https.tls=true"
    depends_on:
      - galaxy-db
    networks:
      intranet:

  galaxy-ui:
    image: ghcr.io/emrahcom/galaxy-kc/galaxy-ui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui-http.entrypoints=reverse-proxy-http"
      - "traefik.http.routers.ui-http.rule=PathPrefix(`/`)"
      - "traefik.http.routers.ui-https.entrypoints=reverse-proxy-https"
      - "traefik.http.routers.ui-https.rule=PathPrefix(`/`)"
      - "traefik.http.routers.ui-https.tls=true"
    depends_on:
      - galaxy-api-adm
      - galaxy-api-pri
      - galaxy-api-pub
    networks:
      intranet:

  reverse-proxy:
    image: "traefik:v2.9"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.reverse-proxy-http.address=:80"
      - "--entrypoints.reverse-proxy-https.address=:443"
    networks:
      intranet:

volumes:
  data:

networks:
  intranet:
